spring.application.name=inventory
spring.data.mongodb.uri=mongodb://localhost:27017/inventorydb
server.port=8080

# optional: increase max http size if large excel/pdf
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
